user = User.find_or_create_by_username! :username => 'root', :name => 'I am Root', :email => 'root@test.com', :password => 'password', :password_confirmation => 'password'

user = User.find_or_create_by_username! :username => 'testuser1', :name => 'I am testing 1', :email => 'user1@test.com', :password => 'password', :password_confirmation => 'password'
user = User.find_or_create_by_username! :username => 'testuser2', :name => 'I am testing 2', :email => 'user2@test.com', :password => 'password', :password_confirmation => 'password'
user = User.find_or_create_by_username! :username => 'testuser3', :name => 'I am testing 3', :email => 'user3@test.com', :password => 'password', :password_confirmation => 'password'
user = User.find_or_create_by_username! :username => 'testuser4', :name => 'I am testing 4', :email => 'user4@test.com', :password => 'password', :password_confirmation => 'password'
user = User.find_or_create_by_username! :username => 'testuser5', :name => 'I am testing 5', :email => 'user5@test.com', :password => 'password', :password_confirmation => 'password'
user = User.find_or_create_by_username! :username => 'testuser6', :name => 'I am testing 6', :email => 'user6@test.com', :password => 'password', :password_confirmation => 'password'
user = User.find_or_create_by_username! :username => 'testuser7', :name => 'I am testing 7', :email => 'user7@test.com', :password => 'password', :password_confirmation => 'password'
user = User.find_or_create_by_username! :username => 'testuser8', :name => 'I am testing 8', :email => 'user8@test.com', :password => 'password', :password_confirmation => 'password'
user = User.find_or_create_by_username! :username => 'testuser9', :name => 'I am testing 9', :email => 'user9@test.com', :password => 'password', :password_confirmation => 'password'

# color = Color.create! :name => 'white'
# color = Color.create! :name => 'black'
# color = Color.create! :name => 'red'
# color = Color.create! :name => 'green'
# color = Color.create! :name => 'orange'
# color = Color.create! :name => 'blue'
# color = Color.create! :name => 'yellow'
# color = Color.create! :name => 'purple'